name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.2"

      - name: Build Go
        run: go build -o api main.go

      - name: Test Go
        run: go test -v ./...

      - name: Build Docker image
        run: |
          docker build -t hamasfa/health:latest .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push Docker image
        run: docker push hamasfa/health:latest

      - name: Deploy
        run: |
          ssh -i "C:/Users/hamas/File Hamas/NETICS/vps-local/.vagrant/machines/default/virtualbox/private_key" \
          -p 2222 \ 
          -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} \
          "docker pull hamasfa/health:latest && \
           docker stop health || true && \
           docker rm health || true && \
           docker run -d --name health -p 80:8080 hamasfa/health:latest"
